/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DiagnosesRouteImport } from './routes/diagnoses'
import { Route as AppearanceRouteImport } from './routes/appearance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRunsRouteImport } from './routes/api/runs'
import { Route as ApiAccessRouteImport } from './routes/api/access'
import { Route as ApiRunsIngestRouteImport } from './routes/api/runs/ingest'
import { Route as ApiRunsRunIdRouteImport } from './routes/api/runs/$runId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosesRoute = DiagnosesRouteImport.update({
  id: '/diagnoses',
  path: '/diagnoses',
  getParentRoute: () => rootRouteImport,
} as any)
const AppearanceRoute = AppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessRoute = ApiAccessRouteImport.update({
  id: '/api/access',
  path: '/api/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsIngestRoute = ApiRunsIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => ApiRunsRoute,
} as any)
const ApiRunsRunIdRoute = ApiRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ApiRunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appearance': typeof AppearanceRoute
  '/diagnoses': typeof DiagnosesRoute
  '/evidence': typeof EvidenceRoute
  '/playbook': typeof PlaybookRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/api/access': typeof ApiAccessRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runs/$runId': typeof ApiRunsRunIdRoute
  '/api/runs/ingest': typeof ApiRunsIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appearance': typeof AppearanceRoute
  '/diagnoses': typeof DiagnosesRoute
  '/evidence': typeof EvidenceRoute
  '/playbook': typeof PlaybookRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/api/access': typeof ApiAccessRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runs/$runId': typeof ApiRunsRunIdRoute
  '/api/runs/ingest': typeof ApiRunsIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appearance': typeof AppearanceRoute
  '/diagnoses': typeof DiagnosesRoute
  '/evidence': typeof EvidenceRoute
  '/playbook': typeof PlaybookRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/api/access': typeof ApiAccessRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runs/$runId': typeof ApiRunsRunIdRoute
  '/api/runs/ingest': typeof ApiRunsIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appearance'
    | '/diagnoses'
    | '/evidence'
    | '/playbook'
    | '/runs'
    | '/settings'
    | '/api/access'
    | '/api/runs'
    | '/api/runs/$runId'
    | '/api/runs/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appearance'
    | '/diagnoses'
    | '/evidence'
    | '/playbook'
    | '/runs'
    | '/settings'
    | '/api/access'
    | '/api/runs'
    | '/api/runs/$runId'
    | '/api/runs/ingest'
  id:
    | '__root__'
    | '/'
    | '/appearance'
    | '/diagnoses'
    | '/evidence'
    | '/playbook'
    | '/runs'
    | '/settings'
    | '/api/access'
    | '/api/runs'
    | '/api/runs/$runId'
    | '/api/runs/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppearanceRoute: typeof AppearanceRoute
  DiagnosesRoute: typeof DiagnosesRoute
  EvidenceRoute: typeof EvidenceRoute
  PlaybookRoute: typeof PlaybookRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  ApiAccessRoute: typeof ApiAccessRoute
  ApiRunsRoute: typeof ApiRunsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnoses': {
      id: '/diagnoses'
      path: '/diagnoses'
      fullPath: '/diagnoses'
      preLoaderRoute: typeof DiagnosesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appearance': {
      id: '/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access': {
      id: '/api/access'
      path: '/api/access'
      fullPath: '/api/access'
      preLoaderRoute: typeof ApiAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/ingest': {
      id: '/api/runs/ingest'
      path: '/ingest'
      fullPath: '/api/runs/ingest'
      preLoaderRoute: typeof ApiRunsIngestRouteImport
      parentRoute: typeof ApiRunsRoute
    }
    '/api/runs/$runId': {
      id: '/api/runs/$runId'
      path: '/$runId'
      fullPath: '/api/runs/$runId'
      preLoaderRoute: typeof ApiRunsRunIdRouteImport
      parentRoute: typeof ApiRunsRoute
    }
  }
}

interface ApiRunsRouteChildren {
  ApiRunsRunIdRoute: typeof ApiRunsRunIdRoute
  ApiRunsIngestRoute: typeof ApiRunsIngestRoute
}

const ApiRunsRouteChildren: ApiRunsRouteChildren = {
  ApiRunsRunIdRoute: ApiRunsRunIdRoute,
  ApiRunsIngestRoute: ApiRunsIngestRoute,
}

const ApiRunsRouteWithChildren =
  ApiRunsRoute._addFileChildren(ApiRunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppearanceRoute: AppearanceRoute,
  DiagnosesRoute: DiagnosesRoute,
  EvidenceRoute: EvidenceRoute,
  PlaybookRoute: PlaybookRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  ApiAccessRoute: ApiAccessRoute,
  ApiRunsRoute: ApiRunsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
